### ISSUE TITLE
Sidebar is not in content DIV

### ISSUE THREAD

**Issue by Ven79** [ColdTrick/blog_tools#32]
The sidebar is not included in content DIV so that I show it on the back and not on the side.

You can see the result to: http://social.leansixsigma.university/blog/view/388/lean-mind

Thanks

**Comment by jdalsem** [comment]
@Ven79 i see what your problem is. I am however not able to determine what is causing the issue, so i can not confirm if this is causes by the blog tools plugin. If you could determine what part of blog tools is causing the issue please let me know.

Are you using the latest community release on your site? Or have you downloaded the latest version of blog_tools from github?

**Comment by venusiano79** [comment]
I'm using the last one downloaded from github. 

Can I give you in private the ftp access so that you you can check if the issue is the plugin or not ?

**Comment by jdalsem** [comment]
@Ven79 you can send login details to jdalsem@coldtrick.com

**Comment by venusiano79** [comment]
I resolved just now,  was the addthis plugin that generate the issues
